### PR TITLE
Feature/custom commands

### PR DESCRIPTION
**Pull request by Cosik**
Test implementation of custom command.
This have to be well tested. Currently tested only on PC.

Info for testers:
Please use this link https://github.com/Cosik/OctoPrint-NavbarTemp/archive/feature/custom-commands.zip to install and test plugin

### CODE REVIEW

**Comment by nppc** [comment]
In general is working good on Armbian.

This setup I used:
image

And this is how status bar looks:
image

**Two minor issues:**
1. The Custom command only appears after Octoprint restart.
2. Space before custom command name is missing.

**Comment by nppc** [comment]
One more issue with storing settings.
Steps to replicate:

1. Configure custom parameter (name and command) and save them.
2. Reopen webpage with Octoprint.
3. Go back to plugin settings - everything is ok.
4. Now change name of the custom command (leave command as it is) and save.
5.  Reopen webpage with Octoprint.
6. Open settings again - now command is disappeared.
7. If you try to enter command again and save. After reopening command again gone.

To be able to store command again, you need to restart Octoprint server.

**Comment by Cosik** [comment]
@nppc thanks for feedback, now those issue should be fixed

**Comment by nppc** [comment]
Thank you! Looks very good! :)

Only one minor issue left with changing the settings. If I change field Name only, then Cmd field is cleared after saving.

**Comment by cristiansavaro** [comment]
Installed on 4xPi3B and 1xPi0W and it works just fine !

screenshot 2018-11-29 17 50 27
screenshot 2018-11-29 17 48 33
screenshot 2018-11-29 17 48 45
screenshot 2018-11-29 17 49 01
screenshot 2018-11-29 18 07 33

**Comment by miweimann** [comment]
Hey , i am new to this stuff. What kind of temp sensors are supportet? I use a DS18B20 on gpio 4 and setup the plugin with the command "gpio read 4", but there is no output to the navbar. The sensor did run with Roomtemp plugin before and is running with the Octopi Enc plugin. So am i wrong with the command i use?

**Comment by cristiansavaro** [comment]
> Hey , i am new to this stuff. What kind of temp sensors are supportet? I use a DS18B20 on gpio 4 and setup the plugin with the command "gpio read 4", but there is no output to the navbar. The sensor did run with Roomtemp plugin before and is running with the Octopi Enc plugin. So am i wrong with the command i use?

The command i run for DS18B20 is the following (gpio read 4 just isn't going to work):

`cat $(find /sys/bus  | grep w1_slave | grep '28-')/w1_slave | grep "t=" | cut -d "=" -f 2 | awk '{printf "%.1f\xc2\xb0C\n", $1/1000}'`

**Comment by miweimann** [comment]
Thanks a lot, it run like a charm. Very nice work!!

BTW: Octoprint 1.3.10 on RPi 3b

**Comment by Cosik** [comment]
To be honest I don't know how to configure this plugin to startup and display on octoprint startup.

**Comment by 101jallen** [comment]
Running on an Intel I3 under Ubunto 18.04 seems to work very well having the CPU temp and CPU fan speed next is to cook the fan speed + cpu load.....
opx86-bar

**Comment by ErSedavi** [comment]
Does someone know the command to show the temp of a DTH11 sensor? It's already running with Enclosure Plugin.

**Comment by ScottWell1** [comment]
Tested this on pi4, Octoprint 1.3.2, with a DS18B20.  Works GREAT!   Used the custom command provided by @cristiansavaro in earlier post.  Changed refresh time from 30s to 10s; would be nice to have that as an option in settings.

Will this PR ever be incorporated into released version?  Been around since Oct-2018, would be nice to see it released.  Thanks!

**Pull request merged**
