### PR TITLE
Themeify support + Fahrenheit support

### PR DESCRIPTION
**Pull request by LazeMSS**
- Added support for Themeify
- Added support for display temps in Fahrenheit
- Hide tool temps when not active/connected

### CODE REVIEW

**Comment by Cosik** [comment]
@LazeMSS could you please add some print screens how it works? Currently I don't use octoprint and don't have any test env for octoprint.

**Comment by LazeMSS** [comment]
With dark standard colors (and my UI Customizer):
image

With dark standard no internal:
image

With fahrenheit enabled:
image

Fullscreen with Themeify discoranged theme:
image

And full with UI Customizer added:
image

**Comment by LazeMSS** [comment]
... PS I would be happy to be a collab :)

**Comment by Cosik** [comment]
@LazeMSS good job :+1: 

Sorry I don't have such power.

**Comment by LazeMSS** [comment]
Happy to help 👍 

Will it be released a new version or?

**Comment by Cosik** [comment]
Yes. I will release it in new version

**Pull request merged**
